server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
